### PR TITLE
Fix token offset calculation

### PR DESCRIPTION
**Pull request by egonelbre**
Fixes https://github.com/Microsoft/vscode-go/issues/1967

`ast.File.Pos()` returns the position of the `package` keyword not the beginning of the file.

### CODE REVIEW

**Comment by mnewswanger** [comment]
I'm still seeing the same error in vscode with this patch applied (using mutli-line comment above package)

**Comment by ramya-rao-a** [comment]
@egonelbre is right.
@mnewswanger After getting the patch run, `go build -o`. Provide the path to your existing `godef-gomod`/ `godef-gomod.exe` file.

cc @ianthehat

**Comment by mnewswanger** [comment]
Confirmed w/ the `godef-gomod` filename

**Comment by KyleHansT** [comment]
Stuck running at 100% CPU

**Pull request merged**
